configure: Add avutil
Signed-off-by: Derek Buitenhuis <derek.buitenhuis@gmail.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -88,7 +88,7 @@ LIBNAME=""
 CXXFLAGS="-Wall -D__STDC_CONSTANT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I. -I$SRCDIR/vs -I$SRCDIR/core"
 LDFLAGS=""
 SOFLAGS="-shared -Wl,-Bsymbolic"
-DEPLIBS="libavformat libavcodec"
+DEPLIBS="libavformat libavcodec libavutil"
 
 # -- options ----------------------------------------------------------------
 echo all command lines: > config.log
@@ -200,6 +200,12 @@ fi
 if ! cc_check "$CXXFLAGS $VSCFLAGS" "$LDFLAGS $LIBS $XLIBS" "VapourSynth.h" "getVapourSynthAPI;" ; then
     log_echo "error: vapoursynth checking failed."
     error_exit "VapourSynth.h might not be installed."
+fi
+
+log_echo "checking for libavutil..."
+if ! cc_check "$CXXFLAGS" "$LDFLAGS $LIBS $XLIBS" "libavutil/avutil.h" "av_get_media_type_string(AVMEDIA_TYPE_VIDEO);" ; then
+    log_echo "error: libavutil checking failed."
+    error_exit "libavutil/avutil.h might not be installed or some libs missing."
 fi
 
 log_echo "checking for libavformat..."
